// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var LogoSvg = require("./logo.svg");
var ReasonReact = require("bs-react/src/ReasonReact.js");

((require('./App.css')));

var component = ReasonReact.component("App");

function make(message, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* jsElementWrapped */component[/* jsElementWrapped */2],
          /* render */(function (param) {
              return React.createElement("div", {
                          className: "App"
                        }, React.createElement("div", {
                              className: "App-header"
                            }, React.createElement("img", {
                                  className: "App-logo",
                                  alt: "logo",
                                  src: LogoSvg
                                }), React.createElement("h2", undefined, message)), React.createElement("p", {
                              className: "App-intro"
                            }, "To get started, edit", React.createElement("code", undefined, " src/App.re "), "and save to reload."));
            })
        ];
}

exports.component = component;
exports.make = make;
/*  Not a pure module */
