// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var ReactDOMRe = require("bs-react/src/ReactDOMRe.js");
var ReasonReact = require("bs-react/src/ReasonReact.js");
var ServiceWorker = require("./serviceWorker");

((require('./index.css')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, App.make("Welcome to BsReact", /* array */[])), "root");

ServiceWorker.unregister();

/*  Not a pure module */
